site_name: PythonLibs-Science
nav:
  - < imt-mobisyst <: '..'
  - Lecture intro.: 'index.md'
  - Basis:
    - OS & language:  'basis-01-system.md'
    - First exos:     'basis-01-exo.md'
    - Object-Oriented Prog.: 'basis-02-poo.md'
  - Good practice:
    - Packaging:      'dev-01-pack.md'
    - Versionning:    'dev-02-tools.md'
    - Integration:    'dev-03-integ.md'

markdown_extensions:
  - attr_list
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

theme:
  name: readthedocs
  highlightjs: true

extra_css:
  - style.css
