site_name: PythonLibs-Science
nav:
  - < imt-mobisyst <: '..'
  - Intro au cours: 'index.md'
  - Les bases:
    - OS et language: 'basis-01-system.md'
    - First exos:     'basis-01-exo.md'
    - OOP:            'basis-02-poo.md'
    - Develloper:     'basis-03-dev.md'

markdown_extensions:
  - attr_list
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

theme:
  name: readthedocs
  highlightjs: true

extra_css:
  - style.css
